---

GENERAL:
  interaction_mode: text

DIALOGUE:
  num_dialogues: 1
  initiative: system

  domain: CamRest

  ontology_path: Domain/Domains/flowershop-rules.json
  db_path: Domain/Domains/flowershop-dbase.db

AGENT_0:
  role: system

  DM:
    policy:
      type: handcrafted

    nlu: dummy
    nlg: dummy


  NLU:
    nlu: dummy

  DST:
    dst: dummy

  NLG:
    nlg: dummy

