---

GENERAL:
  interaction_mode: simulation

  experience_logs:
    save: True
    load: False
    path: Logs/simulate_agenda
  
DIALOGUE:
  num_dialogues: 10
  initiative: system

  domain: CamRest

  ontology_path: Domain/Domains/CamRestaurants-rules.json
  db_path: Domain/Domains/CamRestaurants-dbase.db

AGENT_0:
  role: system

  DM:
    policy:
      type: supervised
  
      train: False
      learning_rate: 0.9
      exploration_rate: 0.995
      discount_factor: 0.95
      learning_decay_rate: 0.95
      exploration_decay_rate: 0.995

      policy_path: Models/CamRestPolicy/Sys/sys_supervised_data
  
  USER_SIMULATOR:
    simulator: agenda
    patience: 5
    pop_distribution: [1.0]
    slot_confuse_prob: 0.0
    op_confuse_prob: 0.0
    value_confuse_prob: 0.0
    nlu: dummy
    nlg: dummy
    
  NLU:
    nlu: dummy
    
  DST:
    dst: dummy
    
  NLG:
    nlg: dummy
  
