---

GENERAL:
  interaction_mode: multi_agent
  agents: 2

  experience_logs:
    save: False
    load: False
    path: Logs/CamRest_MultiAgent_Test

DIALOGUE:
  num_dialogues: 100
  domain: CamRest
  ontology_path: Domain/Domains/CamRestaurants-rules.json
  db_path: Domain/Domains/CamRestaurants-dbase.db
  db_type: sql
#  goals_path: Models/UserSimulator/goals_test.pkl


AGENT_0:
  role: system
  
  DM:
    DST:
      dst: dummy

    policy:
      type: wolf_phc
  
      train: False
      learning_rate: 0.0
      exploration_rate: 0.0
      discount_factor: 0.0
      learning_decay_rate: 0.0
      exploration_decay_rate: 0.0

      policy_path: Models/Policies/Sys/wolf_phc_policy_sys.pkl
  
  NLU:
    nlu: CamRest
    model_path: Models/CamRestNLU/Sys/model
  
  NLG:
    nlg: CamRest
    model_path: Models/CamRestNLG/Sys/model


AGENT_1:
  role: user

  DM:
    DST:
      dst: dummy

    policy:
      type: wolf_phc
  
      train: False
      learning_rate: 0.0
      exploration_rate: 0.0
      discount_factor: 0.0
      learning_decay_rate: 0.0
      exploration_decay_rate: 0.0

      policy_path: Models/Policies/User_0/wolf_phc_policy_usr.pkl
  
  NLU:
    nlu: CamRest
    model_path: Models/CamRestNLU/Usr/model
  
  NLG:
    nlg: CamRest
    model_path: Models/CamRestNLG/Usr/model



